{
 "title": "Power",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "Per hour - 30d",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  'Serveur + Balise VR #1' as metric,\n  value AS \"value\"\nFROM power_history_hourly\nWHERE\n  (ip = '192.168.0.40' OR ip = '192.168.0.41') AND\n  $__timeFilter(date)\nORDER BY 1,2"
    },
    {
     "rawSql": "SELECT\r\n  date AS \"time\",\r\n  'Bureau: PC + 4 Ecrans + TV + Audio + Casque VR + Chargeurs Divers + Balise VR #2' AS metric,\r\n  value AS \"value\"\r\nFROM power_history_hourly\r\nWHERE\r\n  ip = '192.168.0.46' AND\r\n  $__timeFilter(date)\r\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Per day - 6 months",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT\n  date::date AS \"time\",\n 'Serveur + Balise VR #1' metric,\n  value AS \"value\"\nFROM power_history_daily\nWHERE\n  (ip = '192.168.0.40' OR ip = '192.168.0.41') AND\n  $__timeFilter(date)\nORDER BY 2,1"
    },
    {
     "rawSql": "SELECT\r\n  date::date AS \"time\",\r\n   'Bureau: PC + 4 Ecrans + TV + Audio + Casque VR + Chargeurs Divers + Balise VR #2' AS metric,\r\n  value AS \"value\"\r\nFROM power_history_daily\r\nWHERE\r\n  ip = '192.168.0.46' AND\r\n  $__timeFilter(date)\r\nORDER BY 2,1"
    }
   ]
  },
  {
   "title": "Per month - 2y",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  date::date AS \"time\",\n  'Serveur + Balise VR #1' AS metric,\n  value AS \"value\"\nFROM power_history_monthly\nWHERE\n  (ip = '192.168.0.40' OR ip = '192.168.0.41') AND\n  $__timeFilter(date) AND date > '2022-08-01'\nORDER BY 2,1"
    },
    {
     "rawSql": "SELECT\r\n  date::date AS \"time\",\r\n  'Bureau: PC + 4 Ecrans + TV + Audio + Casque VR + Chargeurs Divers + Balise VR #2' AS metric,\r\n  value AS \"value\"\r\nFROM power_history_monthly\r\nWHERE\r\n  ip = '192.168.0.46' AND\r\n  $__timeFilter(date) AND date > '2022-08-01'\r\nORDER BY 2,1"
    }
   ]
  }
 ]
}